export const SET_GOODS_SELECTED = 'SET_GOODS_SELECTED'

export const SET_PACKAGE_SELECTED = 'SET_PACKAGE_SELECTED'

export const SET_ROOM_SELECTED = 'SET_ROOM_SELECTED'

export const SET_ORDINFO = 'SET_ORDINFO'